// Copies ABI arrays from Foundry's `out/` build artifacts into a typed TS
// module the frontend can import. Run `forge build` first.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "../.."); // frontend/scripts -> frontend -> repo root
const outDir = path.join(root, "out");
const targetDir = path.join(root, "frontend/src/generated");

const contracts = [
  { name: "Circle", file: "Circle.sol/Circle.json" },
  { name: "CircleFactory", file: "CircleFactory.sol/CircleFactory.json" },
];

if (!existsSync(outDir)) {
  console.error(`No ${outDir} — run \`forge build\` from the repo root first.`);
  process.exit(1);
}

mkdirSync(targetDir, { recursive: true });

let output = "// AUTO-GENERATED by frontend/scripts/sync-abi.mjs — do not edit by hand.\n\n";
for (const { name, file } of contracts) {
  const artifactPath = path.join(outDir, file);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  output += `export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}

writeFileSync(path.join(targetDir, "abis.ts"), output);
console.log(`Synced ${contracts.map((c) => c.name).join(", ")} ABIs to frontend/src/generated/abis.ts`);
