import { CircleAbi, CircleFactoryAbi } from "@/generated/abis";
import localDeployment from "@/generated/local-deployment.json";
import type { Address } from "viem";
import { anvilLocal, whitechainSepolia } from "@/lib/wagmi";

interface Deployment {
  factory: Address;
  tokens: readonly { symbol: string; address: Address }[];
  // Nothing the app cares about (MemberJoined, Defaulted, CircleDeployed…)
  // can predate the factory itself, so event scans never need to look
  // earlier than this. On a real chain that's not just an optimization —
  // Whitechain's public RPC rejects eth_getLogs ranges over 10,000 blocks,
  // and this chain produces blocks fast enough that "from genesis" always
  // blows through that limit.
  fromBlock: bigint;
}

// Local Anvil's addresses are regenerated by script/DeployLocal.s.sol —
// see frontend/src/generated/local-deployment.json (gitignored). The
// Whitechain addresses are permanent and public; see DEPLOYMENTS.md.
const deployments: Record<number, Deployment> = {
  [anvilLocal.id]: {
    factory: localDeployment.factory as Address,
    tokens: [{ symbol: "mUSD", address: localDeployment.token as Address }],
    fromBlock: 0n,
  },
  [whitechainSepolia.id]: {
    factory: "0x7C6800d3fE6d21bcEfa8064a7920F4404408cBA9",
    tokens: [{ symbol: "mUSD", address: "0xf52b97bedD10727B3DC0172AC8030AB4114de7f8" }],
    fromBlock: 5_116_443n,
  },
};

function deploymentFor(chainId: number): Deployment {
  const deployment = deployments[chainId];
  if (!deployment) throw new Error(`No Cherga deployment known for chain ${chainId}`);
  return deployment;
}

export function getCircleFactoryAddress(chainId: number): Address {
  return deploymentFor(chainId).factory;
}

export function getTokens(chainId: number) {
  return deploymentFor(chainId).tokens;
}

export function getFromBlock(chainId: number): bigint {
  return deploymentFor(chainId).fromBlock;
}

export { CircleAbi, CircleFactoryAbi };
